name: class-obf build

on:
  workflow_dispatch:

env:
  VERSION: "1.0.0"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the source
        uses: actions/checkout@v4
        with:
          path: class-obf

      - name: set up java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: build core
        run: |
          mvn -B clean package -DskipTests --file pom.xml
          mv target/class-obf-${{ env.VERSION }}-jar-with-dependencies.jar class-obf-${{ env.VERSION }}.jar
        working-directory: class-obf

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: class-obf
          path: |
            class-obf-${{ env.VERSION }}.jar
